---
- name: Generate wireguard private key
  ansible.builtin.command: wg genkey
  register: private_key
  changed_when: false

- name: Set wireguard private key
  ansible.builtin.set_fact:
    wireguard_private_key: "{{ private_key.stdout }}"
