---
# tasks file for wireguard
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - wireguard
    state: present

- name: Ensure ip forwarding is set on boot
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1
    state: present
  notify: Restart systemd-sysctl

- name: Get private key if already exists
  ansible.builtin.command: cat /etc/wireguard/private_key.txt
  register: wireguard_get_private_key
  changed_when: false
  failed_when: false

- name: Set private key
  ansible.builtin.set_fact:
    wireguard_private_key: "{{ wireguard_get_private_key.stdout }}"
  when: wireguard_get_private_key.stdout != "" and wireguard_private_key is not defined

- name: Generate wireguard private key
  ansible.builtin.include_tasks: generate_keys.yml
  when: wireguard_private_key is not defined and wireguard_private_key_hash is not defined

- name: Save key on remote
  ansible.builtin.copy:
    content: "{{ wireguard_private_key }}\n"
    dest: /etc/wireguard/private_key.txt
    owner: root
    group: root
    mode: "700"

- name: Copy wireguard config file to remote
  ansible.builtin.template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface_name }}.conf"
    mode: "0644"
  notify: Restart wireguard

- name: Enable wireguard systemd service
  ansible.builtin.systemd:
    name: wg-quick@{{ wireguard_interface_name }}.service
    state: started
    enabled: true
  when: wireguard_test is false or wireguard_test is not defined
