---
# handlers file for wireguard
- name: Restart wg dashboard
  ansible.builtin.service:
    name: wg-dashboard
    state: restarted

- name: Restart wireguard
  ansible.builtin.service:
    name: wg-quick@{{ wireguard_interface_name }}.service
    state: restarted
  when: wireguard_test is false or wireguard_test is not defined

- name: Reload sysctl
  ansible.builtin.command: sysctl -p
  changed_when: true
